export enum ProductSize {
  HARDCOVER = "HARDCOVER",
  POCKET_SIZED = "POCKET_SIZED",
  OVERSIZED = "OVERSIZED",
  A4 = "A4",
}

export enum ProductVolume {
  PICTURE_BOOK = "PICTURE_BOOK",
  CHAPTER_BOOK = "CHAPTER_BOOK",
  EARLY_READER = "EARLY_READER",
  FAIRY_TALE = "FAIRY_TALE",
}

export enum ProductStatus {
  PAUSE = "PAUSE",
  PROCESS = "PROCESS",
  DELETE = "DELETE",
}

export enum ProductCollection {
  ACONOMY = "ACONOMY",
  FANTASY = "FANTASY",
  BIOGRAPHY = "BIOGRAPHY",
  SELF_HELP = "SELF_HELP",
  SCIENCE_FICTION = "SCIENCE_FICTION",
  HISTORY = "HISTORY",
  CHILDREN = "CHILDREN",
  OTHER = "OTHER",
}
